### ISSUE TITLE
Error: Reference to undefined global `Ast_helper'

### ISSUE THREAD

**Issue by philtomson** [stedolan/ppx_stage#12]
I installed ppx_stage as instructed under OCaml 4.05.0

In utop:
```
utop # #use "topfind";;
...
utop # #require "ppx_stage.ppx";;
Error: Reference to undefined global `Ast_helper'

```

**Comment by stedolan** [comment]
Do you have the same issue without using `utop`? (That is, with the plain `ocaml` toplevel)

**Comment by stedolan** [comment]
This looks like the same issue as #6 . Does using `utop-full` fix the problem?
