### ISSUE TITLE
Extension 'code' was not translated

### ISSUE THREAD

**Issue by hadils** [stedolan/ppx_stage#7]
I am using Mac OS X 10.12.6 with ocaml 4.05.0 and followed the README instructions. This error appears when i use utop-full or even ocaml as the toplevel.

<# #use "topfind";;

- : unit = ()
Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

- : unit = ()
# #require "ppx_stage.ppx";;
/Users/hadilsabbagh/.opam/4.05.0/lib/ppx_stage/runtime-lib: added to search path
/Users/hadilsabbagh/.opam/4.05.0/lib/ppx_stage/runtime-lib/ppx_stage.cma: loaded
/Users/hadilsabbagh/.opam/4.05.0/lib/ppx_stage/ppx: added to search path
/Users/hadilsabbagh/.opam/4.05.0/lib/ppx_stage/ppx/./ppx.exe --as-ppx: activated
# let greeting = [%code print_string "Hello!\n"];;
Error: Extension `code' was not translated
>

**Comment by stedolan** [comment]
That is an odd error message. I don't think it's produced by either ppx_stage or OCaml. Are you loading some other packages in your `.ocamlinit`?

**Comment by hadils** [comment]
Here is my `.ocamlinit`:
```
(* Added by OPAM. *)                                                                                                                                                              let () =
  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
  with Not_found -> ()
;;

(* ## added by OPAM user-setup for ocamltop / base ## 3ec62baf6f9c219ae06d9814069da862 ## you can edit, but keep this line *)
#use "topfind";;
(* ## end of OPAM user-setup addition for ocamltop / base ## keep this line *)
#warnings "+9"
  (*
#thread;;
#require "core";;
#require "core.top";;
#require "core_extended";;
#require "core_bench";;
#require "ppx_jane";;
#require "ppx_stage.ppx";;
#require "ctypes";;
#require "ctypes.foreign";;
   *)
```

**Comment by stedolan** [comment]
Hmm. I think this is due to `ppx_jane`, which seems to assume that there are no other ppx rewriters. Does it work if you comment out that line?

**Comment by stedolan** [comment]
Alternatively, try with `ocaml -noinit` to avoid loading any initialisation files.

**Comment by hadils** [comment]
That works.

**Comment by hadils** [comment]
`#require ppx_jane` is the offending line in my `.ocamlinit`.

Thanks,
Hadil
